@host = https://blidfvmocuonucymzuhr.supabase.co
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsaWRmdm1vY3VvbnVjeW16dWhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyMTIzMzEsImV4cCI6MjA1NDc4ODMzMX0.NULCFezJYW5-07KjWpf5_xUCzltcDyUQLyk1D7zDnKc
@id =5aa749da-6246-4d1c-9fd2-b8e1212284d3


### GET
GET  https://viacep.com.br/ws/580380/json/

### GET
GET {{host}}/rest/v1/investments?select=*
apikey: {{token}}
Authorization: Bearer {{token}}


### POST 

POST {{host}}/rest/v1/investments
apikey: {{token}}
Authorization: Bearer {{token}}
Content-Type: application/json
Prefer: return=minimal

{
    "name": "Tesouro Selic 2045",
    "value": 100000,
    "origin": "Tesouro Nacional",
    "category": "Pós",
    "interest": "150% Selic"
}

### PATCH

PATCH {{host}}/rest/v1/investments?id=eq.{{id}}
apikey: {{token}}
Authorization: Bearer {{token}}
Content-Type: application/json
Prefer: return=minimal

{
    "interest": "50% Selic"
}

### DELETE

DELETE {{host}}/rest/v1/investments?id=eq.{{id}}
apikey: {{token}}
Authorization: Bearer {{token}}